<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>CD_ROM;Debug;DVD-5;Release;SingleImage</Configurations>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>App.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Prism.Wpf.7.1.0.431\lib\net45\System.Windows.Interactivity.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="App.ico" />
    <Content Include="App_Data\Parameters\Authentication.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Update="App_Data\Parameters\Mail.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="App_Data\Parameters\Rds.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Content Include="App_Data\Parameters\Service.json" />
    <None Update="Settings\SupportTools.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common\Implem.SupportTools.Common.csproj" />
    <ProjectReference Include="..\LdapSyncTester\Implem.SupportTools.LdapSyncTester.csproj" />
    <ProjectReference Include="..\MailTester\Implem.SupportTools.MailTester.csproj" />
    <ProjectReference Include="..\SysLogViewer\Implem.SupportTools.SysLogViewer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommonServiceLocator" Version="2.0.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>
</Project>