<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Implem.SupportTools.MailTester</RootNamespace>
    <AssemblyName>Implem.SupportTools.MailTester</AssemblyName>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="**\\*.xaml" />
    <None Include="app.config" />
    <None Include="Settings\\MailTester.json" CopyToOutputDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Common\\Implem.SupportTools.Common.csproj" />
  </ItemGroup>

</Project>